### ISSUE TITLE
"Whoops, unable to parse the response" when saving class

### ISSUE THREAD

**Issue by ernopp** [joeferraro/MavensMate-SublimeText#211]
Hi, 

Once in a while when I save a class I see this error message appear in the console. I can always try again to save or wait a bit and the class gets saved so it's not a big deal, but since the message says 'please report this issue' I thought I would..

Compiling: TechnologiesUpdater.cls
Timestamp: Wed, 11 Sep 2013 14:13:18
Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please report this issue at https://github.com/joeferraro/MavensMate-SublimeText
[RESPONSE FROM MAVENSMATE]: Traceback (most recent call last):

  File "<string>", line 301, in <module>

  File "<string>", line 53, in main

  File "<string>", line 104, in compile_selected_metadata

  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_project", line 340, in compile_selected_metadata

  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_client", line 474, in compile_with_tooling_api

TypeError: list indices must be integers, not str

**Comment by pawarmangesh** [comment]
@joeferraro I am getting following result in console while creating a new project using mavensmate -
(Note : I am using Windows 7 (32-bit) and sublime text 3 portable version) 

MavensMate for Sublime Text v4.0.4

Operation: Handling requested operation...
Timestamp: Wed, 22 Apr 2015 23:58:52
   Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging) and post relevant log(s) to a new issue at https://github.com/joeferraro/MavensMate-SublimeText
[RESPONSE FROM MAVENSMATE]: Traceback (most recent call last):

  File "<string>", line 6, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm", line 6, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 6, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 55, in <module>
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.config", line 38, in __get_base_path
AttributeError: 'module' object has no attribute '_MEIPASS'

Could you please help me on this to resolve?

**Comment by ralphcallaway** [comment]
@pawarmangesh I posted a response to your original issue on #566 it looks like you have a bad log path which is breaking things, fix that and you should be good

this is a closed issue, so no one is really looking at them, no need to post the same issue repeatedly
