### ISSUE TITLE
Unable to upgrade projects

### ISSUE THREAD

**Issue by philhawthorn** [joeferraro/MavensMate-SublimeText#304]
Having upgraded to 0.38.0 of the plugin and Mavensmate for Sublime Text v3.4.1 I get the following when I try to upgrade a project I receive the following error:

Traceback (most recent call last): File "", line 12, in File "", line 9, in main File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.request", line 86, in execute File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.request", line 115, in __printr File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/json", line 231, in dumps File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/json.encoder", line 201, in encode File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/json.encoder", line 264, in iterencode File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/json.encoder", line 178, in default TypeError: MaxRetryError("HTTPSConnectionPool(host='eu2.salesforce.com', port=443): Max retries exceeded with url: /services/data/v28.0/tooling/query/?q=Select+NamespacePrefix%2C+SymbolTable%2C+Name+From+ApexClass+Where+Id+IN+%28%2701pb0000000vnyBAAQ%27%2C%2701pb0000000vnt6AAA%27%2C%2701pb0000000voM6AAI%27%2C%2701pb0000000vo7IAAQ%27%2C%2701pb0000000vo5gAAA%27%2C%2701pb0000000vo2AAAQ%27%2C%2701pb0000000voK0AAI

(truncated by me)

Then, the project cannot be used as I get the following error on attempting to save:

   Result: [OPERATION FAILED]:Unable to retrieve password from the keychain store.

**Comment by m0gul** [comment]
GAA, none of these old solutions work, since you've changed to the MM desktop app! I want to revert!!
