### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by kevinpray** [joeferraro/MavensMate-SublimeText#516]
Hi - I am a first time user of sublime/mm and I am being tasked with taking over some consultant's code. My process so far has been:
1. Install Python 2.7.8 for windows, allow use for all users, prepend directory to path
2. Install Sublime build 3.065
3. Install package control
4. Install mavensmate

When I attempt to create a new MM project, I get a blank screen. When looking at the text console, I see the following:
=========
DPI scale: 1
startup, version: 3065 windows x32 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Documents and Settings/kevin_p/Application Data/Sublime Text 3/Packages
state path: /C/Documents and Settings/kevin_p/Application Data/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Documents and Settings/kevin_p/Application Data/Sublime Text 3/Installed Packages
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 172 cache hits: 172
pre session restore time: 0.108574
startup time: 0.140574
first paint time: 0.140574
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
loaded 837 snippets
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
Package Control: Skipping automatic upgrade, last run at 2014-11-17 12:25:31, next run at 2014-11-17 13:25:31 or after
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Documents and Settings\kevin_p\Application Data\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" --ui -o new_project -c SUBLIME_TEXT_3
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\pkg_resources", line 34, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\email.parser", line 12, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\email.feedparser", line 27, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\email.message", line 16, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\email.charset", line 13, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\email.base64mime", line 40, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\email.utils", line 27, in <module>
  File "C:\Users\Administrator\Desktop\PyInstaller-2.1\PyInstaller\loader\pyi_importers.py", line 270, in load_module
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\random", line 885, in <module>
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\random", line 97, in __init__
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\random", line 113, in seed
WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly
=======
There is no "c:\users\Administrator\"  directory. Is there some change in some configuration file I need to make?

Thank you in advance for your help.

**Comment by ralphcallaway** [comment]
@kevinpray what version on windows are you on? other users have experienced other issues with the bundled python executable mm.exe, typically due to bugs in pyinstaller

you might consider trying a clean install of mavensmate and see if that works, otherwise you can work around this issues by using python directly, see option 3 in http://mavensmate.com/Getting_Started/Users to get going with a pip package, alternatively you can run the source code directly, see the instructions under the  "* MavensMate for Sublime Text 3" bullet point in the "Setting Up Your Environmet Section" of http://mavensmate.com/Getting_Started/Developers

**Comment by kevinpray** [comment]
Hi Ralph,

As it turns out, that particular functionality was not available under
WinXP SP3. Once my office machine was upgraded to Win7, I was able to use
Mavensmate.

**Comment by ralphcallaway** [comment]
ahh, good to know, win 7 is the earliest version supported, thanks for the update
