### ISSUE TITLE
Problem installing MM for SublimeText behind corporate firewall/proxy

### ISSUE THREAD

**Issue by DarrinDipity** [joeferraro/MavensMate-SublimeText#556]
Done my best to fix the problem myself, but exhausted my knowledge so reaching out for help.

Used Package Control to install MM (Sublime console output):

````
ignored packages updated to: [Vintage, MavensMate]
found 1 files for base name Default.sublime-theme
reloading Packages/User/Package Control.sublime-settings
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Package Control.sublime-settings
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: an integer is required
reloading plugin MavensMate.util
theme loaded
found 4 files for base name Default.sublime-keymap
generating syntax summary
generating meta info summary
found 3 files for base name Main.sublime-menu
reloading Packages/User/mavensmate.sublime-settings
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
reloading Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded
````

As a result, I see the MM menu option added to SublimeText.  I then go up and select
MavensMate>MavensMate API>Update MavensMate API

````
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: forcing mm installation
[MAVENSMATE]: {'tag_name': 'v0.2.4', 'prerelease': False, 'published_at': '2014-09-08T16:29:45Z', 'html_url': 'https://github.com/joeferraro/mm/releases/tag/v0.2.4', 'target_commitish': 'master', 'url': 'https://api.github.com/repos/joeferraro/mm/releases/543050', 'name': 'v0.2.4', 'body': '- Resolves package.xml parsing issue', 'author': {'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'html_url': 'https://github.com/joeferraro', 'login': 'joeferraro', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'url': 'https://api.github.com/users/joeferraro', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'gravatar_id': '', 'type': 'User', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'id': 54157, 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'created_at': '2014-09-08T16:24:26Z', 'assets': [{'uploader': {'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'html_url': 'https://github.com/joeferraro', 'login': 'joeferraro', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'url': 'https://api.github.com/users/joeferraro', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'gravatar_id': '', 'type': 'User', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'id': 54157, 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-linux.tar.gz', 'download_count': 756, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232483', 'name': 'mm-linux.tar.gz', 'size': 13496681, 'created_at': '2014-09-08T16:32:11Z', 'label': '', 'id': 232483, 'state': 'uploaded', 'content_type': 'application/gzip', 'updated_at': '2014-09-08T16:32:16Z'}, {'uploader': {'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'html_url': 'https://github.com/joeferraro', 'login': 'joeferraro', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'url': 'https://api.github.com/users/joeferraro', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'gravatar_id': '', 'type': 'User', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'id': 54157, 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-osx-v0.2.4.zip', 'download_count': 7354, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232484', 'name': 'mm-osx-v0.2.4.zip', 'size': 11164657, 'created_at': '2014-09-08T16:32:29Z', 'label': None, 'id': 232484, 'state': 'uploaded', 'content_type': 'application/zip', 'updated_at': '2014-09-08T16:32:36Z'}, {'uploader': {'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'html_url': 'https://github.com/joeferraro', 'login': 'joeferraro', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'url': 'https://api.github.com/users/joeferraro', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'gravatar_id': '', 'type': 'User', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'id': 54157, 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip', 'download_count': 12104, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232481', 'name': 'mm-win-v0.2.4.zip', 'size': 11502317, 'created_at': '2014-09-08T16:30:18Z', 'label': '', 'id': 232481, 'state': 'uploaded', 'content_type': 'application/octet-stream', 'updated_at': '2014-09-08T16:30:22Z'}], 'zipball_url': 'https://api.github.com/repos/joeferraro/mm/zipball/v0.2.4', 'assets_url': 'https://api.github.com/repos/joeferraro/mm/releases/543050/assets', 'id': 543050, 'upload_url': 'https://uploads.github.com/repos/joeferraro/mm/releases/543050/assets{?name}', 'draft': False, 'tarball_url': 'https://api.github.com/repos/joeferraro/mm/tarball/v0.2.4'}
[MAVENSMATE]: latest asset ---->
[MAVENSMATE]: {'uploader': {'gists_url': 'https://api.github.com/users/joeferraro/gists{/gist_id}', 'received_events_url': 'https://api.github.com/users/joeferraro/received_events', 'site_admin': False, 'organizations_url': 'https://api.github.com/users/joeferraro/orgs', 'html_url': 'https://github.com/joeferraro', 'login': 'joeferraro', 'subscriptions_url': 'https://api.github.com/users/joeferraro/subscriptions', 'url': 'https://api.github.com/users/joeferraro', 'starred_url': 'https://api.github.com/users/joeferraro/starred{/owner}{/repo}', 'avatar_url': 'https://avatars.githubusercontent.com/u/54157?v=3', 'repos_url': 'https://api.github.com/users/joeferraro/repos', 'gravatar_id': '', 'type': 'User', 'following_url': 'https://api.github.com/users/joeferraro/following{/other_user}', 'id': 54157, 'followers_url': 'https://api.github.com/users/joeferraro/followers', 'events_url': 'https://api.github.com/users/joeferraro/events{/privacy}'}, 'browser_download_url': 'https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip', 'download_count': 12104, 'url': 'https://api.github.com/repos/joeferraro/mm/releases/assets/232481', 'name': 'mm-win-v0.2.4.zip', 'size': 11502317, 'created_at': '2014-09-08T16:30:18Z', 'label': '', 'id': 232481, 'state': 'uploaded', 'content_type': 'application/octet-stream', 'updated_at': '2014-09-08T16:30:22Z'}
[MAVENSMATE]: attempting to download:   https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip
Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 1202, in connect
  File "./http/client.py", line 808, in _tunnel
OSError: Tunnel connection failed: 407 authenticationrequired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\[my login]\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 184, in run
    self.install()
  File "C:\Users\[my login]\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 310, in install
    with urllib.request.urlopen(download_url) as response, open(os.path.join(sublime.packages_path(),"User","MavensMate",zip_name), 'wb') as out_file:
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 475, in open
  File "./urllib/request.py", line 587, in http_response
  File "./urllib/request.py", line 507, in error
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 692, in http_error_302
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1283, in https_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error Tunnel connection failed: 407 authenticationrequired>
[MAVENSMATE]: [MAVENSMATE] could not install mm
[MAVENSMATE]: <urlopen error Tunnel connection failed: 407 authenticationrequired>
[MAVENSMATE]: handling result of mm update!!!
````

The HTTP 407 error leads me to believe it's a problem w/ the proxy setup.  I use Git for all kinds of other reasons though and have all the normal suspects covered.  Our proxy does not require user id/password to be passed to it.

I have `HTTP_PROXY` and `HTTPS_PROXY` set in my Windows Env variables.  Because of corporate restrictions, the `git://` protocol is blocked and subsequently we have to use `https://`, so I have the following 

````
~/.gitconfig

[url "https://"]
    insteadOf = git://
````

To further cover my bases, I add my proxy settings to the MM User Settings:
````
"mm_http_proxy" : "http:\/\/[proxy server]:80",

"mm_https_proxy" : "http:\/\/[proxy server]:80",
````

Would love some fresh eyes to see if I'm missing something.  Really hope to be able to use my trusty Sublime Text editor to connect to our SF org to make changes.

**Comment by ralphcallaway** [comment]
lots of stuff here, trying to focus in on getting you moving

first, doesn't seem to be a git:// protocol issue, the installer is able to get most of the details, i.e. what the release is, but is bonking when downoading the actual zip, perhaps you have some restrictions on your proxy there? you can probably figure it out by trying to access https://github.com/joeferraro/mm/releases/download/v0.2.4/mm-win-v0.2.4.zip directly

you're best option is just to download an install the mm core api manually, although given the proxy is already given you trouble, this is likely to come up again

there is some good stuff at http://mavensmate.com/Getting_Started/Developers for a full manual install but you have some intermediary options that are partially outlined here http://mavensmate.com/Getting_Started/Users

1. just unzip it yourself to standard location
- get that url above and unzip it into <st3 packages>\MavensMate\mm (that's what the installer is usually doing

2. unzip it anywhere else
- you can tell the plugin where to look with the `mm_path` option

3. use the pip package 
- install python and pip if needed
- pip install 
- set `mm_path`

4. full install
- install python
- install all dependencies
- download the mm core
- set mm developer mode to true, set mm python path to python, set mm mm py path to your mm.py file

closing this for now, re-open if none of these options work for you and please include additional diagnostic info
