### ISSUE TITLE
Unable to create New Project from git repository

### ISSUE THREAD

**Issue by karkolomek** [joeferraro/MavensMate-SublimeText#582]
Hi,

I've trying to create new project following this instructions - http://mavensmate.com/Plugins/Sublime_Text/Existing_Projects

But each time I got this error

Traceback (most recent call last): File "", line 12, in File "", line 9, in main File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 95, in execute File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 133, in __printr File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\json", line 243, in dumps File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\json.encoder", line 207, in encode File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\json.encoder", line 270, in iterencode UnicodeDecodeError: 'utf8' codec can't decode byte 0xea in position 21: invalid continuation byte

I am running on win7 64b, sublime is 64b 

Regards,
Karol

**Comment by riadhmankai** [comment]
I have exactly the same problem. Sublime Text 3, Windows 7 64 bit. It has been month I've been trying everything. I've never been able to make Mavensmate work on Windows.

**Comment by georgesguigui** [comment]
Hi,
I have also same problem.
I have upgrade to mavensmate pre-release v5.
I'm then able to create new project, but I have an issue when trying to deploy.

Thanks for any updates regarding this.

Regards,

**Comment by joeferraro** [comment]
@georgesguigui when you say you're having trouble deploying, can you elaborate?

**Comment by georgesguigui** [comment]
Hi,
This is issue "Validate/Deploy to server: System keychain service not supported #642"  I have entered yesterday.
When I deploy with latest pre-release of mavensmate, the following error message appears in Mavensmate: "System keychain service not supported" 

Regards,

**Comment by joeferraro** [comment]
@georgesguigui ah ok, i see you reported here: https://github.com/joeferraro/MavensMate-SublimeText/issues/642

we're looking into it
