### ISSUE TITLE
Not able to create new Project 

### ISSUE THREAD

**Issue by vivek15987** [joeferraro/MavensMate-SublimeText#594]
[OPERATION FAILED]: Could not find the mm executable. Please run MavensMate > Install/Update MavensMate API (mm) to install mm to your MavensMate for Sublime Text plugin directory.

I have tried to update this plugin still its showing same error.

**Comment by praveenmakam2012** [comment]
Same Issue while I try to install on a system under office proxy. It works like charm in our personal laptop.

@joeferraro , I have seen the team asking for logs while we face this issue. Here is the log,

reloading Packages/User/mavensmate.sublime-settings
reloading Packages/User/mavensmate.sublime-settings
reloading Packages/User/mavensmate.sublime-settings
Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 1198, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 520, in run_
    return self.run()
  File "C:\Users\pmakamgovind\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mavensmate.py", line 1381, in run
    mm_installer.execute(printer)
  File "C:\Users\pmakamgovind\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 41, in execute
    thread = MmInstaller(True, printer=printer, **kwargs)
  File "C:\Users\pmakamgovind\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 119, in __init__
    self.release_data   = get_mm_releases()
  File "C:\Users\pmakamgovind\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 93, in get_mm_releases
    releases = urllib.request.urlopen('https://api.github.com/repos/joeferraro/mm/releases').read().decode('utf-8')    
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1283, in https_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by keoryn** [comment]
I have the same problem, since updating to 6.0.0. Mavensmate was connecting with 4.0.5, then I updated to 6.0, and I'm not connecting anymore.

Traceback (most recent call last):
  File "C:\Program Files\SublimeText\sublime_plugin.py", line 520, in run_
    return self.run()
  File "C:\Users\roberwil\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mavensmate.py", line 1385, in run
    mm_installer.execute(printer)
  File "C:\Users\roberwil\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 41, in execute
    thread = MmInstaller(True, printer=printer, **kwargs)
  File "C:\Users\roberwil\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 119, in __init__
    self.release_data   = get_mm_releases()
  File "C:\Users\roberwil\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 93, in get_mm_releases
    releases = urllib.request.urlopen('https://api.github.com/repos/joeferraro/mm/releases').read().decode('utf-8')    
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1283, in https_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by keoryn** [comment]
It seems to be a Package Control issue specifically. I found a workaround using the steps from : https://github.com/wbond/package_control/issues/123#issuecomment-6236536
