### ISSUE TITLE
ST Version 5.0 Delete file issue

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate-SublimeText#599]
Right click file > MavensMate > Delete File From Server

```
ERROR:   
Result: [ERROR]: INVALID_OPERATION: No zip file content passed in

LOGS:
[MAVENSMATE]: OPERATION: delete-metadata
[MAVENSMATE]: {'context': <MavensMate.mavensmate.DeleteActiveMetadataCommand object at 0x10d89d1d0>, 'body': {'paths': ['/Users/kyle/workspace/MercDev3/src/classes/GLBL_AccountToAccountRollups.cls']}}
[MAVENSMATE]: http://localhost:59011/execute?command=delete-metadata&async=1&pid=1537FN3AP8TVJQ0NSJGUTAO2QKXEGF0O
[MAVENSMATE]: b'{"paths": ["/Users/kyle/workspace/MercDev3/src/classes/GLBL_AccountToAccountRollups.cls"]}'
[MAVENSMATE]: {'id': '48452700-2a2b-11e5-9c0c-87d1be186352', 'operation': 'delete-metadata', 'error': 'INVALID_OPERATION: No zip file content passed in', 'complete': True, 'stack': 'sf:INVALID_OPERATION: INVALID_OPERATION: No zip file content passed in\n    at HttpApi.getError (/Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:240:13)\n    at /Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:85:22\n    at /Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/lib/core.js:33:15\n    at flush (/Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)\n    at process._tickCallback (node.js:355:11)'}
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'id': '48452700-2a2b-11e5-9c0c-87d1be186352', 'operation': 'delete-metadata', 'error': 'INVALID_OPERATION: No zip file content passed in', 'complete': True, 'stack': 'sf:INVALID_OPERATION: INVALID_OPERATION: No zip file content passed in\n    at HttpApi.getError (/Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:240:13)\n    at /Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/lib/http-api.js:85:22\n    at /Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/lib/core.js:33:15\n    at flush (/Users/kyle/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/mavensmate/node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)\n    at process._tickCallback (node.js:355:11)'}
[MAVENSMATE] failed to send community activity
```

**Comment by kylethornton** [comment]
SILLY logging: https://gist.github.com/kylethornton/8c48979c439a06a3d6e2

**Comment by kylethornton** [comment]
Mavensmate.log under Silly logging: https://gist.github.com/kylethornton/8da15d3b1c430ea52af8

**Comment by kylethornton** [comment]
For posterity: Issue seems to lie in node version. Using 0.12. Switching to 0.10.33 as working around.

**Comment by joeferraro** [comment]
https://github.com/jsforce/jsforce/issues/241

**Comment by joeferraro** [comment]
tracking here: https://github.com/joeferraro/MavensMate/issues/471
