### ISSUE TITLE
[Errno 10054] : Can not create new project

### ISSUE THREAD

**Issue by michacom** [joeferraro/MavensMate-SublimeText#640]
Before there was a strange problem, on SubimeText start, the MM package reported a failure, something like "the MM server was not started..." (sorry I do not remember). After remove/install (via Package Control), that problem was not reported, from now I'm faced with new one.
Any attempt to create/edit/update/compile a project rejected with `[Errno 10054] An existing connection was forcibly closed by the remote host` message.

the console dump:
```
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: compile
[MAVENSMATE]: {'params': {'files': ['C:\\<<MavensMate Workspace>>\\<<Project Name>>\\<<FileName>>']}, 'context': <sublime.View object at 0x000000114B16F400>}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: "C:\Users\USER\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -o compile -c SUBLIME_TEXT_3
[MAVENSMATE]: {"project_name": "MichaelSimkin home", "files": ["C:\\<<MavensMate Workspace>>\\<<Project Name>>\\<<FileName>>"], "workspace": "C:/<<MavensMate Workspace>>"}<<Project Name>>]: response from mm: {"body": "[Errno 10054] An existing connection was forcibly closed by the remote host", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 69, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 61, in __setup_connection\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 75, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client\", line 102, in __init__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client\", line 108, in login\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sforce.base\", line 490, in login\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 542, in __call__\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 602, in invoke\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client\", line 637, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 77, in send\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http\", line 118, in u2open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 404, in open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 422, in _open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 382, in _call_chain\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1222, in https_open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2\", line 1187, in do_open\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 1067, in getresponse\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 409, in begin\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib\", line 365, in _read_status\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\socket\", line 476, in readline\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl\", line 246, in recv\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl\", line 165, in read\nerror: [Errno 10054] An existing connection was forcibly closed by the remote host\n", "success": false}

[MAVENSMATE]: HANDLING COMPILE!
[MAVENSMATE]: {'success': False, 'body': '[Errno 10054] An existing connection was forcibly closed by the remote host', 'stack_trace': 'Traceback (most recent call last):\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request", line 69, in execute\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request", line 61, in __setup_connection\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project", line 75, in __init__\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client", line 102, in __init__\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client", line 108, in login\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sforce.base", line 490, in login\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client", line 542, in __call__\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client", line 602, in invoke\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.client", line 637, in send\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http", line 77, in send\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\suds.transport.http", line 118, in u2open\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2", line 404, in open\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2", line 422, in _open\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2", line 382, in _call_chain\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2", line 1222, in https_open\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\urllib2", line 1187, in do_open\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib", line 1067, in getresponse\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib", line 409, in begin\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\httplib", line 365, in _read_status\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\socket", line 476, in readline\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl", line 246, in recv\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\ssl", line 165, in read\nerror: [Errno 10054] An existing connection was forcibly closed by the remote host\n'}
[MAVENSMATE] failed to send community activity
```

OS: Win8.1
SublimeText3 startup console dump:
```
DPI scale: 1
startup, version: 3083 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/USER/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/USER/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/USER/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Markdown", "CSS", "Vintage"]
pre session restore time: 0.118686
warning: mnemonic t not found in menu caption Tools
startup time: 0.143686
first paint time: 0.143686
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Advanced CSV.csvplugin
=== NumPy disabled, using TinyNumPy instead ===
To enable cell evaluation using the full NumPy, download NumPy from:
    https://pypi.python.org/pypi/numpy
and install it into Sublime Text's Packages directory.
For information on the features and limitations of TinyNumPy, visit:
    https://github.com/wadetb/tinynumpy
======================
reloading plugin AngularJS.AngularJS-sublime-package
reloading plugin AngularJS.jscompletions
reloading plugin AngularJS.message
reloading plugin AngularJS.sublime_commands
reloading plugin AngularJS.viewlocation
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin ChannelRepositoryTools.ordereddict
reloading plugin ChannelRepositoryTools.tests
reloading plugin ChannelRepositoryTools.upgrade
reloading plugin Compare Side-By-Side.sbs_compare
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin CSS3.validator
reloading plugin CTags.ctags
reloading plugin CTags.ctagsplugin
reloading plugin CTags.test_ctags
reloading plugin CTags.test_ctagsplugin
reloading plugin DocBlockr.jsdocs
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin Google Search.google_search
reloading plugin InsertDate.insert_date
reloading plugin LineEndings.LineEndings
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.gather_missing_links
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.insert_references
reloading plugin MarkdownEditing.jumpToMarker
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.list_markdown_references
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.paste_as_link
reloading plugin MarkdownEditing.paste_as_reference
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin npm.cli
reloading plugin npm.command
reloading plugin npm.install
reloading plugin npm.link
reloading plugin npm.list
reloading plugin npm.rm
reloading plugin npm.run_arbitrary
reloading plugin npm.search
reloading plugin npm.test
reloading plugin npm.update
reloading plugin Package Control.bootstrap
reloading plugin Package Control.Package Control
reloading plugin Preferences Editor.Preferences Editor
reloading plugin Pretty JSON.PrettyJson
[WinError 2] The system cannot find the file specified
reloading plugin xml2json.ordereddict
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "ordereddict in C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed Packages\xml2json.sublime-package", line 23, in <module>
ImportError: No module named 'UserDict'
reloading plugin xml2json.Xml2json
reloading plugin xml2json.xmltodict
reloading plugin Cheat Sheets.cheat-sheets
reloading plugin DocBlokr.jsdocs
reloading plugin JSHint.JSHint
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
InsertDate settings changed
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
Package Control: Skipping automatic upgrade, last run at 2015-08-23 15:39:59, next run at 2015-08-23 16:39:59 or after
[MAVENSMATE] failed to send community activity
```

thanks

**Comment by joeferraro** [comment]
Nothing changed on our side, this is likely a Salesforce issue. Until it's proven this is a MavensMate issue, will close.

**Comment by michacom** [comment]
ok, last try.
There is a stack trace, fetched with Fiddler (development proxy server)
````
stack_trace=Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 93, in execute
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.commands.project", line 39, in execute
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.project", line 112, in retrieve_and_write_to_disk
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client", line 96, in __init__
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client", line 108, in login
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sforce.base", line 490, in login
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\suds.client", line 542, in __call__
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\suds.client", line 602, in invoke
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\suds.client", line 637, in send
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\suds.transport.http", line 77, in send
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\suds.transport.http", line 118, in u2open
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\urllib2", line 404, in open
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\urllib2", line 422, in _open
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\urllib2", line 382, in _call_chain
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\urllib2", line 1222, in https_open
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\urllib2", line 1187, in do_open
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\httplib", line 1067, in getresponse
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\httplib", line 409, in begin
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\httplib", line 373, in _read_status
BadStatusLine: ''
````

I'm not a pithoner, so I can not to debug this.
