### ISSUE TITLE
Cann't refresh all project metadata

### ISSUE THREAD

**Issue by SergeyTrusov** [joeferraro/MavensMate-SublimeText#668]
When select src folder and click "Refresh from Server.." get following error:
[ERROR]: Cannot read property 'inFolder' of undefined

**Comment by joeferraro** [comment]
This is a known issue on Windows. I assume you're on Windows? The workaround until a fix is released is to clean your project which does the same thing as refreshing the src folder.

**Comment by SergeyTrusov** [comment]
Yes, problem occurred on Windows.
Clean will delete all file from my local dir that doesn't exist on server. It isn't applicable for me.

**Comment by amilabdallah** [comment]
This is an issue for me on OSX as well.

**Comment by joeferraro** [comment]
@amilabdallah please set up logs in mm-app's settings panel and paste any relevant logs, as this is not an known issue on OSX

**Comment by amilabdallah** [comment]
==================> executing command: refresh-metadata

2015-10-02T17:46:58.698Z - info: executeCommandForProject payload is: {"paths":["//users/amilabdallah/Documents/mavensmate/Core"]}
2015-10-02T17:46:58.698Z - debug: command class is: RefreshMetadataCommand
2015-10-02T17:46:58.699Z - debug: refreshing paths from server ...
2015-10-02T17:46:58.702Z - debug: Could not complete refresh request: Cannot read property 'inFolder' of undefined
2015-10-02T17:46:58.702Z - info: handling command result: 
2015-10-02T17:46:58.702Z - error:  TypeError: Cannot read property 'inFolder' of undefined
    at Object.defineProperty.get (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/file.js:211:18)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/file.js:542:48
    at arrayFilter (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:1384:13)
    at Function.filter (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:6309:14)
    at Object.module.exports.getLightningBundleItemFiles (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/file.js:542:12)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:99:51
    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at RefreshDelegate._refreshLocalPaths (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:83:10)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:42:10
    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at RefreshDelegate.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:41:10)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/metadata/refresh-metadata.js:34:40
2015-10-02T17:46:58.703Z - debug: finishing jobid: 9449d6a0-692d-11e5-b30c-2905c2df66cc
2015-10-02T17:46:58.703Z - error:  TypeError: Cannot read property 'inFolder' of undefined
    at Object.defineProperty.get (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/file.js:211:18)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/file.js:542:48
    at arrayFilter (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:1384:13)
    at Function.filter (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:6309:14)
    at Object.module.exports.getLightningBundleItemFiles (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/file.js:542:12)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:99:51
    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at RefreshDelegate._refreshLocalPaths (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:83:10)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:42:10
    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at RefreshDelegate.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/refresh.js:41:10)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/metadata/refresh-metadata.js:34:40
2015-10-02T17:46:58.704Z - debug: Processing request GET for URL: /status?id=9449d6a0-692d-11e5-b30c-2905c2df66cc
2015-10-02T17:46:58.704Z - debug: query params id=9449d6a0-692d-11e5-b30c-2905c2df66cc

**Comment by joeferraro** [comment]
@amilabdallah so is your project called "CORE"? Can you paste your package.xml?

**Comment by amilabdallah** [comment]
Yes the project is called Core

<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>CustomLabels</name>
    </types>
    <types>
        <members>*</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>*</members>
        <name>CustomObjectTranslation</name>
    </types>
    <types>
        <members>*</members>
        <name>Document</name>
    </types>
    <types>
        <members>*</members>
        <name>EmailTemplate</name>
    </types>
    <types>
        <members>*</members>
        <name>HomePageComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>HomePageLayout</name>
    </types>
    <types>
        <members>*</members>
        <name>Layout</name>
    </types>
    <types>
        <members>*</members>
        <name>PermissionSet</name>
    </types>
    <types>
        <members>*</members>
        <name>Queue</name>
    </types>
    <types>
        <members>*</members>
        <name>RemoteSiteSetting</name>
    </types>
    <types>
        <members>*</members>
        <name>ReportType</name>
    </types>
    <types>
        <members>*</members>
        <name>Role</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <types>
        <members>*</members>
        <name>Workflow</name>
    </types>
    <version>34.0</version>
</Package>

**Comment by joeferraro** [comment]
is this a new project (created after v5) or an old project? if this is an old project, can you re-create the project and see whether that resolves the issue?

**Comment by amilabdallah** [comment]
This was a project created after v5, but I will test again by creating a new project for sanity sake

**Comment by joeferraro** [comment]
It looks like it may be blowing up when trying to refresh your lightning bundles. Can you tell me a little more about those? How many there are, what types, etc?

**Comment by amilabdallah** [comment]
I have my project path defined as
[
  "users/amilabdallah/Documents/mavensmate"
]

**Comment by joeferraro** [comment]
change your workspace to this, restart mm-app, and see whether it helps:
```
[
  "/Users/amilabdallah/Documents/mavensmate"
]
```

"users/amilabdallah/Documents/mavensmate" is not a valid path

**Comment by amilabdallah** [comment]
I was able to resolve the issue by:

1. updating the path in mavensmate settings 
2. closing both mavensmate and sublimetext 
3. Deleting the old workspace folder
4. Make a new workspace folder (same name and path as the one I deleted)
5. Create a new project

**Comment by joeferraro** [comment]
ok thanks @amilabdallah

**Comment by figosat** [comment]
Hi,
I can't refresh customMetadata folder i get this error `[ERROR]: Cannot read property 'inFolder' of undefined`

I'm using MavensMate for Sublime Text v7.0.0-beta.3.
Have some issue to resolve this problem. Thks a lot.
