### ISSUE TITLE
Error initializing project: Unrecognized package.xml metadata type: AccountCriteriaBasedSharingRule

### ISSUE THREAD

**Issue by force2b** [joeferraro/MavensMate-SublimeText#693]
I'm getting this error due to the following metadata types in the Package.xml. All of these worked fine in v4.

* AccountCriteriaBasedSharingRule
* AccountOwnerSharingRule
* CampaignCriteriaBasedSharingRule
* CampaignOwnerSharingRule
* CaseCriteriaBasedSharingRule
* CaseOwnerSharingRule
* ContactCriteriaBasedSharingRule
* ContactOwnerSharingRule
* CustomObjectCriteriaBasedSharingRule
* CustomObjectOwnerSharingRule
* LeadCriteriaBasedSharingRule
* LeadOwnerSharingRule
* OpportunityCriteriaBasedSharingRule
* OpportunityOwnerSharingRule

MM Version: 5.004
MM-App Version: v.0.0.9

Log:
```
2015-10-05T13:15:42.495Z - debug: Processing request POST for URL: /execute?command=refresh-metadata&async=1&pid=QGKE1TMX1K8R2KJ66LZXJJMFJ8RPVX8P
2015-10-05T13:15:42.496Z - debug: post body paths=[C:\SalesForce.com\MavensMate\hl-salesforce\src\classes\CCx_ViewClientController.cls]
2015-10-05T13:15:42.498Z - debug: _findProjectPathById
2015-10-05T13:15:42.498Z - debug: QGKE1TMX1K8R2KJ66LZXJJMFJ8RPVX8P
2015-10-05T13:15:42.498Z - debug:  0=C:\SalesForce.com\MavensMate, 1=C:\SalesForce.com\Atom-Workspace
2015-10-05T13:15:42.499Z - debug: C:\SalesForce.com\MavensMate
2015-10-05T13:15:42.505Z - debug: [TRUNCATED TO REMOVE CLASS NAMES]
2015-10-05T13:15:42.535Z - debug: C:\SalesForce.com\Atom-Workspace
2015-10-05T13:15:42.536Z - debug: [TRUNCATED TO REMOVE CLASS NAMES]
2015-10-05T13:15:42.537Z - info: adding project by id ---->  QGKE1TMX1K8R2KJ66LZXJJMFJ8RPVX8P
2015-10-05T13:15:42.537Z - info: path:  C:\SalesForce.com\MavensMate\hl-salesforce
2015-10-05T13:15:42.538Z - debug: initing existing project ...
2015-10-05T13:15:42.540Z - debug: project name hl-salesforce
2015-10-05T13:15:42.540Z - debug: project path C:\SalesForce.com\MavensMate\hl-salesforce
2015-10-05T13:15:42.541Z - debug: initing package instance
2015-10-05T13:15:42.541Z - debug: deserializing: C:\SalesForce.com\MavensMate\hl-salesforce\src\package.xml
2015-10-05T13:15:42.633Z - debug: parsed package.xml to -->{"AccountCriteriaBasedSharingRule":"*","AccountOwnerSharingRule":"*","ApexClass":"*","ApexComponent":"*","ApexPage":"*","ApexTrigger":"*","ApprovalProcess":"*","AssignmentRules":"*","CampaignCriteriaBasedSharingRule":"*","CampaignOwnerSharingRule":"*","CaseCriteriaBasedSharingRule":"*","CaseOwnerSharingRule":"*","ContactCriteriaBasedSharingRule":"*","ContactOwnerSharingRule":"*","CustomApplication":"*","CustomLabels":"*","CustomObject":"*", [TRUNCATED TO REMOVE CLASS NAMES]
2015-10-05T13:15:42.640Z - debug: setting package subscription: 
2015-10-05T13:15:42.641Z - debug:  AccountCriteriaBasedSharingRule=*, AccountOwnerSharingRule=*, ApexClass=*, ApexComponent=*, ApexPage=*, ApexTrigger=*, ApprovalProcess=*, AssignmentRules=*, CampaignCriteriaBasedSharingRule=*, CampaignOwnerSharingRule=*, CaseCriteriaBasedSharingRule=*, CaseOwnerSharingRule=*, ContactCriteriaBasedSharingRule=*, ContactOwnerSharingRule=*, CustomApplication=*, CustomLabels=*, CustomObject=*, CustomObjectCriteriaBasedSharingRule=[], CustomObjectOwnerSharingRule=[], CustomPageWebLink=*, CustomPermission=*, CustomSite=*, CustomTab=*, Dashboard=[  [TRUNCATED TO REMOVE CLASS NAMES]
2015-10-05T13:15:42.650Z - debug: initiating SalesforceClient: 
2015-10-05T13:15:42.651Z - debug: initializing connection to salesforce ...
2015-10-05T13:15:42.651Z - debug: logging in to salesforce: https://test.salesforce.com/
2015-10-05T13:15:43.592Z - debug: getting user information:
2015-10-05T13:15:43.805Z - debug: logged in successfully
2015-10-05T13:15:43.806Z - debug: configuring jsforce ...
2015-10-05T13:15:44.137Z - debug: writing local session
2015-10-05T13:15:44.355Z - error: Could not initiate existing Project instance: Unrecognized package.xml metadata type: AccountCriteriaBasedSharingRule
2015-10-05T13:15:44.361Z - error: Error initializing project: Unrecognized package.xml metadata type: AccountCriteriaBasedSharingRule -> Error: Unrecognized package.xml metadata type: AccountCriteriaBasedSharingRule
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\project.js:1013:37
    at C:\Program Files\MavensMate\resources\app\node_modules\lodash\index.js:3073:15
    at baseForOwn (C:\Program Files\MavensMate\resources\app\node_modules\lodash\index.js:2046:14)
    at Function.<anonymous> (C:\Program Files\MavensMate\resources\app\node_modules\lodash\index.js:3378:16)
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\project.js:1010:21
    at tryCatch1 (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:45:21)
    at Promise._callHandler (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:571:13)
    at Promise._settlePromiseFromHandler (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAt (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:733:18)
    at Promise._settlePromiseAtPostResolution (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:339:10)
    at Async._consumeFunctionBuffer (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:85:12)
    at Async.consumeFunctionBuffer (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\async.js:40:14)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```

**Comment by joeferraro** [comment]
@force2b certainly apologize for the inconvenience, but it's virtually impossible for us to support every legacy API construct. As the documentation notes, those metadata types have been deprecated as of 33.0 and are replaced with `SharingRules` (which we support) 

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_cbsrule.htm

I can certainly have a look at what it would take to support those types, but it's not a high priority at the moment given bandwidth.

**Comment by force2b** [comment]
@joeferraro Thanks for the quick response. Actually I didn't realize that those were deprecated. This project comes out of a git repo. I'll work with the client to get the package.xml updated accordingly.

Though, in v4 it was possible to set the working API version in the User or Project settings. I don't see that in v5. I'm asking because this worked up to last week when I was still running v4. The package.xml itself has <version>32.0</version> in it. Is there a way to set the API version to use for projects?

**Comment by joeferraro** [comment]
You can find `mm_api_version` in mm-app's global settings. We are exploring the re-implementation of project-specific settings in an upcoming release: https://github.com/joeferraro/MavensMate/issues/490

**Comment by force2b** [comment]
Hmm. I'm wondering if the API calls to get the metadata should be using the API version set in the global settings? I changed that value from 34.0 to 32.0 and then re-ran Clean Project to see if it would pick up the older sharing types (ex: AccountCriteriaBasedSharingRule). I got the same error though. I would have expected that to work if it were using the v32 API.
