### ISSUE TITLE
Error when Removing v5

### ISSUE THREAD

**Issue by dsumnerMWA** [joeferraro/MavensMate-SublimeText#695]
Hi,

Im having save issues with just about every save with v5 and need to rollback to v4. Your instructions say v5 needs to be removed through Package Control, but when I try to do so I get the following in the console:

Traceback (most recent call last):
  File "package_control.commands.remove_package_command in C:\Users\myuser\Sublime Text 3\Packages\Package Control.sublime-package", line 59, in on_done
  File "package_control.package_disabler in C:\Users\myuser\Sublime Text 3\Packages\Package Control.sublime-package", line 74, in disable_packages
ImportError: No module named 'package_control'

Also - if I completely uninstall sublime text 3 and reinstall following the instructions for v4, Sublime Text just sits and does nothing.

**Comment by dsumnerMWA** [comment]
This may have been an issue with local permissions with the new version. Closing for now.
