### ISSUE TITLE
list indices must be integers, not str

### ISSUE THREAD

**Issue by LKozakewycz** [joeferraro/MavensMate-SublimeText#708]
Whenever I try to compile apex:

```
[MAVENSMATE]: HANDLING COMPILE!
[MAVENSMATE]: {'body': 'list indices must be integers, not str', 'stack_trace': 'Traceback (most recent call last):\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request", line 93, in execute\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.metadata", line 340, in execute\n  File "C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.sfdc_client", line 319, in compile_with_tooling_api\nTypeError: list indices must be integers, not str\n', 'success': False}
```

MM 5.00
ST 3083
Win 8.1

**Comment by LKozakewycz** [comment]
Worked around this by switching to metadata API, compiling and finding out there was a trigger name mismatch. Fixed, compiled (MDAPI) successfully and switched back to the Tooling API and compiled again successfully. Attempting to rename the trigger again did not cause an unexpected issue and threw the appropriate error message.
