### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by vabs** [joeferraro/MavensMate-SublimeText#752]
OS: Windows 10, 64 bit
MM: MavensMate for Sublime Text v6.0.0
Sublime Text: 3.0
No Firewall
When refreshing the source code, I get error below.

[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.project", line 351, in clean
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.util", line 255, in extract_base64_encoded_zip
  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\base64", line 73, in b64decode
MemoryError

**Comment by brijeshk1931** [comment]
Hi, Im facing the same problem mentioned above. If anyone came across this issue and has a fix. Please help me.

Thanks in advance
