### ISSUE TITLE
ImportError: No module named 'MavensMate'

### ISSUE THREAD

**Issue by mbotos** [joeferraro/MavensMate-SublimeText#812]
With the new MavensMate-app running and Sublime plugin v7 installed, Sublime logs the following errors during startup:

reloading plugin MavensMate-SublimeText.mavensmate
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/matthew/Library/Application Support/Sublime Text 3/Packages/MavensMate-SublimeText/mavensmate.py", line 12, in <module>
    import MavensMate.config as config
ImportError: No module named 'MavensMate'
reloading plugin MavensMate-SublimeText.util
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/matthew/Library/Application Support/Sublime Text 3/Packages/MavensMate-SublimeText/util.py", line 10, in <module>
    import MavensMate.config as config
ImportError: No module named 'MavensMate'

**Comment by mbotos** [comment]
Looks like this was an install issue. Fixed by manually downloading MavensMate-sublime and copying into ~/Library/Application Support/Sublime Text 3/Packages/MavensMate-SublimeText.
