### ISSUE TITLE
[ERROR]: Cannot read property 'xmlName' of undefined

### ISSUE THREAD

**Issue by vabs** [joeferraro/MavensMate-SublimeText#840]
Platform: Windows 10 - 64 Bit
Sublime Text: Version 3.0 - Build 3114
MavensMate: MavensMate-SublimeText 7.0.0  + MavensMate-app v0.0.10

Steps to reproduce:
When creating new Static Resources.

MM Logs:

`
2016-09-13T13:07:39.370Z - error:  TypeError: Cannot read property 'xmlName' of undefined
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\resource-bundle.js:39:17
    at arrayEach (C:\Program Files\MavensMate\resources\app\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (C:\Program Files\MavensMate\resources\app\node_modules\lodash\index.js:3345:13)
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\resource-bundle.js:33:7
    at tryCatch2 (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:53:21)
    at Promise._resolveFromResolver (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:544:13)
    at new Promise (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:82:37)
    at ResourceBundleService.create (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\resource-bundle.js:28:10)
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\commands\resource-bundle\new-resource-bundle.js:25:19
    at tryCatch2 (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:53:21)
    at Promise._resolveFromResolver (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:544:13)
    at new Promise (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:82:37)
    at Command.execute (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\commands\resource-bundle\new-resource-bundle.js:22:10)
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\client.js:380:21
    at tryCatch2 (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\util.js:53:21)
    at Promise._resolveFromResolver (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\node_modules\bluebird\js\main\promise.js:544:13)
2016-09-13T13:07:39.371Z - debug: Processing request GET for URL: /status?id=0c4a1f70-79b3-11e6-b520-ff8e0ab67de4
2016-09-13T13:07:39.371Z - debug: query params id=0c4a1f70-79b3-11e6-b520-ff8e0ab67de4
`

**Comment by joeferraro** [comment]
This issue was moved to joeferraro/MavensMate#739
