### ISSUE TITLE
READ ECONNRESET

### ISSUE THREAD

**Issue by aragornrok** [joeferraro/MavensMate-SublimeText#847]
Getting this error a lot now. on edit project as well as on create project.

Please find log below.

2016-09-29T05:50:39.717Z - error: unpackaged retrieveRequest error: read ECONNRESET
2016-09-29T05:50:39.717Z - error: Could not index metadata type CustomObject: read ECONNRESET
2016-09-29T05:50:39.717Z - error: Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T05:50:39.717Z - error: Could not index children/folders for CustomObject: read ECONNRESET
2016-09-29T05:50:39.717Z - error: An error occurred indexing server properties
2016-09-29T05:50:39.717Z - error: read ECONNRESET
2016-09-29T05:50:39.717Z - error: Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T05:50:39.718Z - error: Could not index metadataHelper: read ECONNRESET
2016-09-29T05:50:39.718Z - info: handling command result: 
2016-09-29T05:50:39.718Z - error:  Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T05:50:39.718Z - debug: finishing jobid: 81fb01b0-8608-11e6-af6d-ddacd5915b60
2016-09-29T05:50:39.718Z - error:  Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T05:50:40.032Z - debug: Processing request GET for URL: /status?id=2dca3090-8606-11e6-af6d-ddacd5915b60
2016-09-29T05:50:40.032Z - debug: query params id=2dca3090-8606-11e6-af6d-ddacd5915b60
2016-09-29T05:50:40.034Z - debug: Processing request GET for URL: /status?id=060dce80-8607-11e6-af6d-ddacd5915b60

Windows 

Version 7.0.1 desktop app .10

EDit: Getting this only when custom object is one of the subscription components.
unselected that and its working.

So why is custom object failing.

edit 2:
Even on sucessfull save of files i am getting the same error. 
The file changes are reflected in sandbox.

edit 3:
I went down to version 6 and for the same org , same sublime text i am not facing any read econnreset errors be it on save or create or edit project.

**Comment by aragornrok** [comment]
Another one today:
2016-09-29T07:25:51.669Z - debug: command class is: NewProjectCommand
2016-09-29T07:25:51.669Z - debug: initiating SalesforceClient: 
2016-09-29T07:25:51.669Z - debug: initializing connection to salesforce ...
2016-09-29T07:25:51.669Z - debug: logging in to salesforce: https://test.salesforce.com/
2016-09-29T07:25:51.677Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:25:51.677Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:25:53.349Z - debug: getting user information:
2016-09-29T07:25:54.615Z - debug: logged in successfully
2016-09-29T07:25:54.616Z - debug: configuring jsforce ...
2016-09-29T07:25:54.683Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:25:54.683Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:25:56.003Z - debug: Initiated new project, prepping to write to disk
2016-09-29T07:25:57.197Z - debug: retrieving unpackaged: 
2016-09-29T07:25:57.197Z - debug:  ApexClass=*, ApexTrigger=*
2016-09-29T07:25:57.687Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:25:57.687Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:00.691Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:00.691Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:03.695Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:03.695Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:06.698Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:06.698Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:09.703Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:09.703Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:12.710Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:12.710Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:15.714Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:15.714Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:18.717Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:18.717Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:21.722Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:21.722Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:24.726Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:24.726Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:27.199Z - error: unpackaged retrieveRequest error: read ECONNRESET
2016-09-29T07:26:27.200Z - error: Could not retrieve and write project to file system: read ECONNRESET
2016-09-29T07:26:27.200Z - error: Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T07:26:27.202Z - debug: Could not create project: 
2016-09-29T07:26:27.202Z - debug: Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T07:26:27.202Z - info: handling command result: 
2016-09-29T07:26:27.202Z - error:  Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T07:26:27.203Z - debug: finishing jobid: f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:27.203Z - error:  Error: read ECONNRESET
    at exports._errnoException (util.js:814:11)
    at TLSWrap.onread (net.js:541:26)
2016-09-29T07:26:27.729Z - debug: Processing request GET for URL: /status?id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:27.729Z - debug: query params id=f35b9740-8615-11e6-8b92-63e54141d8b9
2016-09-29T07:26:27.733Z - silly: Processing request GET for URL: /app/static/fonts/Flat-UI-Icons.woff
2016-09-29T07:26:27.741Z - silly: Processing request GET for URL: /app/static/sounds/ding.mp3
